# Generated by Django 3.1.1 on 2021-01-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('properties', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Marrried'), ('Divorce', 'Divorce')], default='SINGLE', max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=20)),
                ('stateoforigin', models.CharField(blank=True, choices=[('ABUJA (FCT)', 'Abuja(FCT)'), ('ABIA', 'Abia'), ('ANAMBRA', 'Anambra'), ('ADAMAWA', 'Adamawa'), ('BAUCHI', 'Bauchi'), ('BAYELSA', 'Bayelsa'), ('BENUE', 'Benue'), ('Borno', 'Borno'), ('CROSS RIVER', 'Cross river'), ('DELTA', 'Delta'), ('EBONYI', 'Ebonyi'), ('EKITI', 'Ekiti'), ('ENUGU', 'Enugu'), ('GOMBE', 'Gombe'), ('IMO', 'Imo'), ('JIGAWA', 'Jigawa'), ('KADUNA', 'Kaduna'), ('KANO', 'Kano'), ('KASTINA', 'Katsina'), ('KEBBI', 'Kebbi'), ('KWARA', 'Kwara'), ('Kogi', 'Kogi'), ('LAGOS', 'Lagos'), ('NASARAWA', 'Nasarawa'), ('NIGER', 'Niger'), ('OGUN', 'Ogun'), ('ONDO', 'Ondo'), ('OSUN', 'Osun'), ('OYO', 'Oyo'), ('OGUN', 'Ogun'), ('PLATEAU', 'Plateau'), ('RIVERS', 'Rivers'), ('PLATEAU', 'Plateau'), ('SOKOTO', 'Sokoto'), ('TARABA', 'Taraba'), ('YOBE', 'Yobe'), ('ZAMFARA', 'Zamfara')], default='ABUJA (FCT)', max_length=30)),
                ('dateofbirth', models.DateField()),
                ('occupation', models.CharField(max_length=50)),
            ],
        ),
    ]
