# Generated by Django 3.1.1 on 2021-02-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='properties',
        ),
        migrations.AddField(
            model_name='forms',
            name='location',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
