# Generated by Django 3.1.1 on 2021-01-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SliderName', models.CharField(max_length=200)),
                ('slider1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('slider2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('slider3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('position', models.CharField(max_length=200)),
                ('hire_date', models.DateField()),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('whatsApp', models.CharField(max_length=100)),
                ('is_mvp', models.BooleanField(default=False)),
            ],
        ),
    ]
