# Generated by Django 3.1.1 on 2021-01-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landsale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('image1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('details', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('landsize', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('listingDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
