# Generated by Django 3.1.1 on 2021-01-26 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('image1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('aka', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('modelyear', models.DateField()),
                ('color', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('listingDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pages.team')),
            ],
        ),
    ]
