# Generated by Django 3.1.1 on 2021-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='modelyear',
            field=models.CharField(max_length=20),
        ),
    ]
